### ISSUE TITLE
Passing parameter to Dangerfile?

### ISSUE THREAD

**Issue by peacemoon** [danger/swift#213]
We have an app project with different targets. In Jenkins we run some steps parallel for all targets. Is it possible to read environment variables or passing data to dangerfile so that we can determine for which target we are running danger?

**Comment by f-meloni** [comment]
Passing a parameter I think is not possible, mainly because we send the parameters to `danger-js` but I don’t think it sends back the parameters it doesn’t know when it calls back danger-swift.
About the environment variable I’m not sure if you can access an exported env variable from the dangerfile but is possible, you should check the environment in `Process`.
An easy alternative, but not perfectly clean, solution, given you are in the CI, could be to write it in a file and read it from the dangerfile.

**Comment by peacemoon** [comment]
"An easy alternative, but not perfectly clean, solution, given you are in the CI, could be to write it in a file and read it from the dangerfile." -> this would be a solution. Thank you for suggestion.

**Comment by AvdLee** [comment]
For anyone visiting this thread as a result of finding out how to access environment variables, you can do that using:

```swift
ProcessInfo.processInfo.environment["Environment_key"]
```

This can also be used for passing parameters into a Dangerfile.swift.
