### ISSUE TITLE
Failed to Parse JSON Bitbucket Cloud

### ISSUE THREAD

**Issue by khoogheem** [danger/swift#277]
Danger installed with Homebrew:

## What did you do?
Trying to run danger-swift on a pr located on Bitbucket Cloud
danger-swift pr <url>

## What happened instead?
```
ERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "from", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "bitbucket_cloud", intValue: nil), CodingKeys(stringValue: "activities", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "comment", intValue: nil), CodingKeys(stringValue: "inline", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"from\", intValue: nil) (\"from\").", underlyingError: nil))

ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/ck/j34wj3q54js1p0vlgvr2rkch0000gn/T/danger-response.json
```

* Are you running the latest version of Danger?
installed from home-brew

* What is your Dangerfile?

```swift
import Danger
import Foundation

let danger = Danger()

SwiftLint.lint(configFile: ".swiftlint.yml")
  ```

**Comment by f-meloni** [comment]
Ok looks like that `from` on Inline comments is optional, let me fix that :)

**Comment by f-meloni** [comment]
I just released the 2.0.5 that fixes that, unfortunately I don't have a project on bitbucket cloud where I can test danger-swift, then is possible that `from` was not the only thing that is optional and we parse as mandatory, in case feel free to re open this issue, or fix the problems yourself with a PR to this repo :)

**Comment by khoogheem** [comment]
```ERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "to", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "bitbucket_cloud", intValue: nil), CodingKeys(stringValue: "activities", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "comment", intValue: nil), CodingKeys(stringValue: "inline", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"to\", intValue: nil) (\"to\").", underlyingError: nil))
```

just tried 2.0.5
Looks like a few more probably should be optional

**Comment by f-meloni** [comment]
`to` is optional ad well apparently. I can not help much, because if I fix it, I need to make a new release every time, and then we need to check if is fixed.
Feel free to make a try if you want, then you can fix one by one all the optional variables.
I would be happy to help you :)
Unfortunately when I builded I it I've followed the danger js DSL object where they were required

**Comment by f-meloni** [comment]
`to` is optional as well apparently. I can not help much, because if I fix it, I need to make a new release every time, and then we need to check if is fixed.
Feel free to make a try if you want, then you can fix one by one all the optional variables.
I would be happy to help you :)
Unfortunately when I builded I it I've followed the danger js DSL object where they were required
