### ISSUE TITLE
Running from non-root directory

### ISSUE THREAD

**Issue by JosephDuffy** [danger/swift#300]
I'm trying to have the `Package.swift` file that contains the `danger-swift` dependency be in a subdirectory of my project, but I'm running in to some issues with Danger/SwiftLint.

If I move my `Package.swift`, `Dangerfile.swift`, and node-related files in to a subdirectory called `DevelopmentDependencies` and run `swift run danger-swift local --danger-js-path (yarn bin danger) --verbose` within that directory SwiftLint never picks up any errors/warnings.

I am running SwiftLint in my Dangerfile via `SwiftLint.lint(directory: "../")`, but `SwiftLint.lint()` also does not work. When run via `swift run swiftlint --path "../"` I get the warnings I expect.

If I only move the `Package.swift` and run it from the root via `swift run --package-path ./DevelopmentDependencies/ danger-swift local --danger-js-path (yarn bin danger) --verbose` it yields an error:

```
Launching Danger Swift local (v2.0.6)
Running: /PROJECT_ROOT/node_modules/.bin/danger local --process danger-swift --passURLForDSL --verbose
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn danger-swift ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn danger-swift',
  path: 'danger-swift',
  spawnargs: []
}
```

Is there a way to do this?

**Comment by f-meloni** [comment]
This is not possible at the moment in the way you are trying to do it I think.

But there are two alternatives:
- You can keep the Dangerfile in another folder, but have `Package.swift` in your main folder, and run danger from the main folder with `--dangerfile DevelopmentDependencies/Dangerfile.swift`
- Swiftlint would need to accept the files list as alternative to the directory in https://github.com/danger/swift/blob/master/Sources/Danger/Plugins/SwiftLint/SwiftLint.swift#L17
This is because `directory` just filters the modified and created files but the paths danger gets are always relative to your main repo (then they never start with `../`).
Adding that option would allow you to pass the files manually and use `.map { :../" + $0 }`

I also think that what you have there could work if you put `lintAll` to true, because in that case it runs it in the directory you specified (`..`), but don't think is what you actually want

**Comment by JosephDuffy** [comment]
Using `lintAllFiles` is working, thanks! It's honouring the `.swiftlint.yml` in my root and subdirectories and showing linting errors/warnings.

It looks like danger is finding the files and passing them to SwiftLint? But this option has SwiftLint finding the files?

The goal was to move the `Package.swift` out of the main folder because it makes working on the framework within another project easier because Xcode will only download/build the dependencies in the root `Package.swift`, so when danger etc. are in the root it slows down package resolution in Xcode.

**Comment by f-meloni** [comment]
To give more context, this is what happens:

- When you use `lintAllFiles` with directory danger calls Swiftlint directly and passes to it the directory you want to lint.
- When you don't use it danger takes all the files that are modified or created on your PR, filters out the one that doesn't have in the path the directory you want, and passes them to Swiftlint.

Now given your path doesn't have `../` in the path (they are relative to the root of the project), everything will be filtered out.
You could use the directory path relative from your root, but in that case Swiftlint wouldn't find the files.

This is why my best suggestion, if you don't want to lint all the files, would be change Swiflint to accept also a list of files to lint then you can change the file paths as you prefer (like by adding `../` to every path and filtering out what you want).
Otherwise lint `lintAllFiles` should be ok

**Comment by JosephDuffy** [comment]
> To give more context, this is what happens:
> 
>     * When you use `lintAllFiles` with directory danger calls Swiftlint directly and passes to it the directory you want to lint.
> 
>     * When you don't use it danger takes all the files that are modified or created on your PR, filters out the one that doesn't have in the path the directory you want, and passes them to Swiftlint.
> 
> 
> Now given your path doesn't have `../` in the path (they are relative to the root of the project), everything will be filtered out.
> You could use the directory path relative from your root, but in that case Swiftlint wouldn't find the files.
> 
> This is why my best suggestion, if you don't want to lint all the files, would be change Swiflint to accept also a list of files to lint then you can change the file paths as you prefer (like by adding `../` to every path and filtering out what you want).
> Otherwise lint `lintAllFiles` should be ok

Thanks for the content, I see why it would be better (performance) to not use `lintAllFiles`, but it sounds like that's not currently possible.

I'm thinking that if Danger were to use full paths and expand the `../` then it could work? I'd be interested in trying to get this to work.

For my current projects using `lintAllFiles` is ok, so if you want to close this issues please go ahead.

**Comment by ecerney** [comment]
I was running into this same issue recently while trying to move all of the Danger related files out of the root to keep things more organized and to avoid Xcode thinking my project was a SPM module because of the Package.swift at the root. I worked out the following solution as a workaround:

I'm running the following command from CI:
`(cd scripts/swift/Danger/ && swift run danger-swift ci --dangerfile DangerFilePreChecks.swift --verbose --id PreChecks)`

And I'm setting an ENV variable for the relative path to the `.swiftlint.yml` file:
`SWIFTLINT_CONFIG_FILE="../../../.swiftlint.yml"

And using that config location within my Dangerfile:
`let configFile = ProcessInfo.processInfo.environment["SWIFTLINT_CONFIG_FILE"] ?? ".swiftlint.yml"`

This allows me to move the danger related files (including the Package.swift) out of the root and into a separate folder.

**Comment by f-meloni** [comment]
@ecerney but the paths are still relative to your repo root folder, how did you solve that?
if you run `cd scripts/swift/Danger/ && swift run danger-swift ci --dangerfile DangerFilePreChecks.swift --verbose --id PreChecks` and let's suppose in your PR you modified `File.swift` (assuming you are not using lintAll with a directory path), it will try to lint `scripts/swift/Danger/Files.swift` no?

**Comment by ecerney** [comment]
Hmm I see what you're saying, but it works for me without the lintAll option.

Lets use the following as an example structure:
scripts
    swift
        Danger
            DangerFilePreChecks.swift
Sources
    Files.swift
.swiftlint.yml

So I believe in specifying where the .yml file is, swiftlint then uses that as the relative root for files to lint. Perhaps danger-swiftlint gets the relative path from github like `Sources/Files.swift` and then adds an absolute path based on the absolute path of the .yml file?

`cd scripts/swift/Danger/ && swift run danger-swift ci --dangerfile DangerFilePreChecks.swift --verbose --id PreChecks` will make the current directory `scripts/swift/Danger`. In `DangerFilePreChecks.swift`, we pass the .yml path as `FileManager.default.currentDirectoryPath + "/" + configFile` aka `Home/MyProject/scripts/swift/Danger/../../../.swiftlint.yml` aka `Home/MyProject/.swiftlint.yml`. Then swiftlint uses that as the root at which to lint files.

**Comment by AlkisPDiscovery** [comment]
For anyone new that experiences this issue, as you will find in the Repo's documentation. You can add the `--pwd relative/path/to/working/directory`

This is the simplest way to not add the "lintAllFiles" option. 
if you have the Package.swift in a directory called for example "Danger" in the root, then the steps to run relative to the root would be

1. `cd` to where the package is located eg. `Danger`
2. run `swift run danger-swift pr [URLOFThePR] --cwd ../`

this will set in danger the current working directory to be the root of the project and not the directory you are running it from. SwiftLint works like a charm.

**Comment by sonic555gr** [comment]
For anyone new that experiences this issue, as you will find in the Repo's documentation. You can add the `--pwd relative/path/to/working/directory`

This is the simplest way to not add the "lintAllFiles" option.
 if you have the `Package.swift` in a directory called for example `Danger` in the root, then the steps to run relative to the root would be

1. `cd` to where the package is located eg. Danger
2. run `swift run danger-swift pr [URLOFThePR] --cwd ../`

this will set in danger the current working directory to be the root of the project and not the directory you are running it from. SwiftLint works like a charm.

**Comment by nikolaykasyanov** [comment]
Hey folks, it looks like this is a solved problem now? As mentioned above, there's `--cwd` to set working directory, and there's also `--dangerfile` to point danger-swift to its Dangerfile. Is there something missing to call it done?

**Comment by f-meloni** [comment]
Closing because the issue looks solved, if you still have issues with this feel free to re open it
